{
 "title": "Home",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "CO₂ level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "ppm",
   "valueName": "avg",
   "targets": [
    { "expr": "co2" }
   ]
  },
  {
   "title": "CO₂ level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "co2" }
   ]
  }
 ]
}